version: '3.8'

services:
  websocket-chat:
    image: boosterko/websocket-chat:${GITHUB_SHA}
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: boosterko/websocket-chat-nginx:${GITHUB_SHA}
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - websocket-chat
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    environment:
        EMAIL: ${EMAIL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 30d & wait $${!}; done;'"
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge
