version: '3.8'
services:
  websocket-chat:
    image: boosterko/websocket-chat:${GITHUB_SHA}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    restart: always

  nginx:
    image: boosterko/websocket-chat-nginx:${GITHUB_SHA}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - websocket-chat
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/var/lib/letsencrypt:/var/lib/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; done;'"
    command: >
      bash -c 'if ! [ -e "/etc/letsencrypt/live/boosterko.com/fullchain.pem" ]; then
        certbot certonly --webroot --webroot-path=/var/www/certbot --email boosterko@google.com --agree-tos --no-eff-email -d boosterko.com -d www.boosterko.com --deploy-hook "nginx -s reload";
      else
        certbot renew --deploy-hook "nginx -s reload";
      fi && while :; do sleep 12h & wait $$!; done;'
    depends_on:
      - nginx