version: '3.8'

services:
  websocket-chat:
    image: boosterko/websocket-chat:${GITHUB_SHA}
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    networks:
      - app-network

  nginx:
    image: boosterko/websocket-chat-nginx:${GITHUB_SHA}
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
    depends_on:
      - websocket-chat
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    environment:
        EMAIL: ${EMAIL}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d www.boosterko.kr -d boosterko.kr
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge
