version: '3.8'
services:
  websocket-chat:
    image: boosterko/websocket-chat:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    restart: always
  nginx:
    image: boosterko/websocket-chat-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - websocket-chat
