version: '3.8'
services:
  websocket-chat:
    image: boosterko/websocket-chat:${{ github.sha }}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    restart: always
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - websocket-chat
