name: Deploy to AWS EC2

on:
  push:
    branches:
      - docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application
        run: |
          ./gradlew clean build -x test
          ls -l build/libs/
          pwd

      - name: Build Docker image
        run: |
          docker build -t boosterko/websocket-chat:${{ github.sha }} .
          docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push boosterko/websocket-chat:${{ github.sha }}


      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
              docker pull boosterko/websocket-chat:${{ github.sha }}
              docker stop websocket-chat || true
              docker rm websocket-chat || true
              docker run -d --restart always --name websocket-chat \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -p 8080:8080 boosterko/websocket-chat:${{ github.sha }}
